/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

import amiss.service.ActionResult;
import amiss.service.GameServices;
import amiss.service.JobService;
import amiss.service.StatsService;
import amiss.service.TimeService;

/**
 * The Bank Screen
 * @author The Rourke
 */
public class BankGUI extends javax.swing.JFrame {

    /**
     * Creates new form BankGUI
     */
    User user;
    DB db;

    private TimeService dist;
    private JobService job;
    private StatsService stat;

    /**
     *
     * @param u user object
     * @param d db object
     */
    public BankGUI(User u, DB d) {
        initComponents();

        user = u;
        db = d;
        GameServices services = new GameServices(u, d);
        dist = services.time();
        job = services.jobs();
        stat = services.stats();

       lblTimer.setText(dist.getNewTime(0)); //gets the time left in the round
        lblMoney.setText(Integer.toString(stat.getCash())); //gets the users cash

        btnWork.setVisible(false);

        String loc = job.getLocation(); //checks if the user works at this location
        if (loc.equals("Bank")) {
            btnWork.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblCash = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblMoney = new javax.swing.JLabel();
        btnWork = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 59, 26));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 13, 72, 26));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 36));

        lblCash.setText("Cash");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, 59, 26));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        txaNotification.setText("Welcome to the Bank ");
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, 260, 187));
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 53, 72, 26));

        btnWork.setText("Work");
        btnWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkActionPerformed(evt);
            }
        });
        getContentPane().add(btnWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 290, 110, 36));

        lblBackground.setIcon(amiss.Assets.icon("screens/Bank.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        BankGUI.this.dispose(); //closes the screen
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkActionPerformed
        ActionResult result = stat.workMain(); //checks if the user has enough time to work and updates their cash
        txaNotification.setText(txaNotification.getText() + result.message());
        if (result.timer() != null) {
            lblTimer.setText(result.timer());
        }
        if (result.money() != null) {
            lblMoney.setText(result.money());
        }
    }//GEN-LAST:event_btnWorkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnWork;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
