/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

import amiss.repository.UserRepository;
import amiss.repository.UserStatsRepository;
import java.sql.SQLException;
import java.util.Optional;

/**
 * The Login Screen
 * @author The Rourke
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        lblConfirmPassword.setVisible(false);
        pwdConfirmPassword.setVisible(false);
        btnCreateUser.setVisible(false);

    }
    DB db = new DB();
    UserRepository users = new UserRepository(db);
    UserStatsRepository userStats = new UserStatsRepository(db);
    String user, passwrd;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txfUserName = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        pwdConfirmPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblGameName = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setText("     User Name");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 79, 104, -1));

        lblPassword.setText("     Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 119, 104, -1));

        lblConfirmPassword.setText("Confirm Password");
        getContentPane().add(lblConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 159, -1, -1));
        getContentPane().add(txfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 76, 170, -1));

        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 116, 170, -1));
        getContentPane().add(pwdConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 156, 170, -1));

        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, -1));

        lblGameName.setText("ROUND ROAD");
        getContentPane().add(lblGameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 116, 45));

        btnCreateUser.setText("Create New User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 376, 20));

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, -1));

        lblBackground.setIcon(amiss.Assets.icon("screens/Login.png"));
        lblBackground.setText("Help");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            user = txfUserName.getText().trim();
            passwrd = pwdPassword.getText();
            if (Validation.isValidUsername(user) && passwrd.length() != 0) { //checks the fields hold a valid username + a password
                Optional<String> storedPassword = users.findPasswordHash(user); //fetches the stored hash for the username
                if (storedPassword.isPresent()) { //checks if user exists in database
                    String stored = storedPassword.get();
                    if (PasswordHasher.matches(passwrd, stored)) { //verifies the password against the stored hash
                        if (PasswordHasher.needsRehash(stored)) { //transparently upgrade a legacy plaintext password
                            users.updatePassword(user, PasswordHasher.hash(passwrd));
                        }
                        User newUser = users.findByName(user).get(); //loads the player's saved state
                        new MainGameGUI(newUser, db).setVisible(true);
                        this.dispose(); //closes the login GUI
                    } else {
                        lblError.setText("Incorrect Password"); //Message Guide for the user
                    }
                } else {
                    lblError.setText("User Does Not Exist");
                    lblConfirmPassword.setVisible(true); //sets fields visible to create a new user
                    pwdConfirmPassword.setVisible(true);
                    btnCreateUser.setVisible(true);
                }
            } else {
                lblError.setText("Please Input a Valid Username and Password"); //messgae guide to the user
            }
        } catch (SQLException ex) {
            lblError.setText("Cannot Load User");//message guide to the user
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        try {
            String conf = pwdConfirmPassword.getText();//retrives the text from the password text field
            if (!Validation.isValidPassword(passwrd)) {
                lblError.setText("Password must be at least " + Validation.MIN_PASSWORD_LENGTH + " characters");
            } else if (conf.equals(passwrd)) { //Checks if both passwords entered by the user match
                users.insertNewUser(user, PasswordHasher.hash(passwrd)); //creates the new user with a hashed password
                userStats.insertNewStats(user);
                lblError.setText("User Added");//message guide to the user
                User newUser = new User(user, 0, 0, 720, 100, 1, "Unemployed", 1, 1, 0, 0);//create new user object
                UserGoals newUserGoals = new UserGoals(user, 0, 0, 0, 0);//creates new userGoal object
                new MainGameGUI(newUser, db).setVisible(true);
                this.dispose();
            } else {
                lblError.setText("Passwords Do Not Match");//message guide to user
            }
        } catch (SQLException s) {
            lblError.setText("Cannot Add New User");
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        new HelpGUI().setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblGameName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField pwdConfirmPassword;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txfUserName;
    // End of variables declaration//GEN-END:variables
}
