/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

/**
 * The Market Screen
 * @author The Rourke
 */
public class MarketGUI extends javax.swing.JFrame {

    /**
     * Creates new form MarketGUI
     */
    static User user;
    static DB db;

    static CalcDuration dist = new CalcDuration();
    static GetAJob job = new GetAJob();
    static Stats stat = new Stats();
    static Food eat = new Food();

    /**
     *
     * @param u user object
     * @param d db object
     */
    public MarketGUI(User u, DB d) {
        initComponents();

        user = u;
        db = d;

        lblTimer.setText(dist.getNewTime(0)); //gets the time left in the round
        lblMoney.setText(Integer.toString(stat.getCash())); //gets the users cash

        btnWork.setVisible(false);

        String loc = job.getLocation(); //checks if the user works at this location
        if (loc.equals("Market")) {
            btnWork.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblCash = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblMoney = new javax.swing.JLabel();
        btnWork = new javax.swing.JButton();
        btn1Weeks = new javax.swing.JButton();
        lbl1Weeks = new javax.swing.JLabel();
        lbl2Weeks = new javax.swing.JLabel();
        btn2Weeks = new javax.swing.JButton();
        lbl4Weeks = new javax.swing.JLabel();
        btn4Weeks = new javax.swing.JButton();
        lbl8Weeks = new javax.swing.JLabel();
        btn8Weeks = new javax.swing.JButton();
        lblShopItems = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Market");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 6, 59, 26));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 6, 130, 26));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 36));

        lblCash.setText("Cash");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 45, 59, 26));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        txaNotification.setText("Welcome to the Market");
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, 270, 129));
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 45, 72, 26));

        btnWork.setText("Work");
        btnWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkActionPerformed(evt);
            }
        });
        getContentPane().add(btnWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 36));

        btn1Weeks.setText("25");
        btn1Weeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1WeeksActionPerformed(evt);
            }
        });
        getContentPane().add(btn1Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 60, -1));

        lbl1Weeks.setText("1 Weeks of Food");
        getContentPane().add(lbl1Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 127, 27));

        lbl2Weeks.setText("2 Weeks of Food");
        getContentPane().add(lbl2Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 127, 27));

        btn2Weeks.setText("48");
        btn2Weeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1WeeksActionPerformed(evt);
            }
        });
        getContentPane().add(btn2Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 60, -1));

        lbl4Weeks.setText("4 Weeks of Food");
        getContentPane().add(lbl4Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 127, 27));

        btn4Weeks.setText("90");
        btn4Weeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1WeeksActionPerformed(evt);
            }
        });
        getContentPane().add(btn4Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 60, -1));

        lbl8Weeks.setText("8 Weeks of Food");
        getContentPane().add(lbl8Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 127, 27));

        btn8Weeks.setText("140");
        btn8Weeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1WeeksActionPerformed(evt);
            }
        });
        getContentPane().add(btn8Weeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 60, -1));

        lblShopItems.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblShopItems.setText("Shop Items");
        getContentPane().add(lblShopItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, 40));

        lblBackground.setIcon(amiss.Assets.icon("screens/Market.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 490, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        MarketGUI.this.dispose(); //closes the screen
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkActionPerformed
        stat.workMain(txaNotification, lblTimer, lblMoney); //checks if the user has enough time to work and updated their cash
    }//GEN-LAST:event_btnWorkActionPerformed

    private void btn1WeeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1WeeksActionPerformed
        int food = 0; //gets the food value of the item purchased
        switch (evt.getActionCommand()) {
            case "25":
                food = 1;
                break;
            case "48":
                food = 2;
                break;
            case "90":
                food = 4;
                break;
            case "140":
                food = 8;
                break;
            default:
                txaNotification.setText("An Error occured");
                break;
        }
        
        String time = dist.getNewTime(1); //checks if the user has enough time and cash to pay for item
        if (time.equals("Not Enough Time")) {
            txaNotification.setText(txaNotification.getText() + "\n" + time);
        } else if (stat.getCash() < Validation.parseIntOrDefault(evt.getActionCommand(), 0)) {
            txaNotification.setText(txaNotification.getText() + "\nNot Enough Cash, You only have R" + stat.getCash());
        } else {
            txaNotification.setText(txaNotification.getText() + "\n" + stat.buy(evt.getActionCommand()));
            eat.setFood(food,txaNotification);
            lblTimer.setText(time);
            lblMoney.setText(Integer.toString(stat.getCash()));
        }
    }//GEN-LAST:event_btn1WeeksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketGUI(user, db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1Weeks;
    private javax.swing.JButton btn2Weeks;
    private javax.swing.JButton btn4Weeks;
    private javax.swing.JButton btn8Weeks;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnWork;
    private javax.swing.JLabel lbl1Weeks;
    private javax.swing.JLabel lbl2Weeks;
    private javax.swing.JLabel lbl4Weeks;
    private javax.swing.JLabel lbl8Weeks;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblShopItems;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
