/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

import amiss.service.ActionResult;
import amiss.service.GameServices;
import amiss.service.JobService;
import amiss.service.StatsService;
import amiss.service.TimeService;

/**
 * The Rent Office Screen
 * @author The Rourke
 */
public class RentOfficeGUI extends javax.swing.JFrame {

    /**
     * Creates new form RentOfficeGUI
     */
    User user;
    DB db;

    private TimeService dist;
    private JobService job;
    private StatsService stat;

    /**
     *
     * @param u user object
     * @param d db object
     */
    public RentOfficeGUI(User u, DB d) {
        initComponents();

        user = u;
        db = d;
        GameServices services = new GameServices(u, d);
        dist = services.time();
        job = services.jobs();
        stat = services.stats();

       lblTimer.setText(dist.getNewTime(0)); //gets the time left in the round
        lblMoney.setText(Integer.toString(stat.getCash())); //gets the users cash

        btnWork.setVisible(false);

        String loc = job.getLocation(); //checks if the user works at this location
        if (loc.equals("Rent Office")) {
            btnWork.setVisible(true);
        }

        if (Integer.parseInt(dist.getRound()) % 4 == 0 && stat.getRent() == 1) { //checks if its the 4th round and the user must pay rent
            btnRent.setVisible(true);
        } else {
            btnRent.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblCash = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblMoney = new javax.swing.JLabel();
        btnRent = new javax.swing.JButton();
        btnWork = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rent Office");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 6, 59, 26));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 6, 72, 26));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 36));

        lblCash.setText("Cash");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 45, 59, 26));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        txaNotification.setText("Rent will be due every 4 rounds\nat R80, to pay rent, simply\ncome the the rent office\nevery 4th round.\nIf your rent isn't paid in time\nYour salary will be reduced until\nthe made up amount is covered");
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, 290, 187));
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 45, 72, 26));

        btnRent.setText("Pay Rent");
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });
        getContentPane().add(btnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 90, 36));

        btnWork.setText("Work");
        btnWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkActionPerformed(evt);
            }
        });
        getContentPane().add(btnWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 90, 36));

        lblBackground.setIcon(amiss.Assets.icon("screens/RentOffice.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        RentOfficeGUI.this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkActionPerformed
        ActionResult result = stat.workMain();
        txaNotification.setText(txaNotification.getText() + result.message());
        if (result.timer() != null) {
            lblTimer.setText(result.timer());
        }
        if (result.money() != null) {
            lblMoney.setText(result.money());
        }
    }//GEN-LAST:event_btnWorkActionPerformed

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        if (dist.getNewTime(0).equals("0:0")) {
            txaNotification.setText(txaNotification.getText() + "\nRound Has Ended");
        } else if (stat.getCash() < 80) {
            txaNotification.setText(txaNotification.getText() + "\nNot Enough Cash, You only have R" + stat.getCash());
            lblMoney.setText(Integer.toString(stat.getCash()));
        } else {
            lblTimer.setText(dist.getNewTime(1));
            stat.setRent(0);
            txaNotification.setText(txaNotification.getText() + "\n" + stat.buy(Integer.toString(80)) + "\nThank you for paying your rent");
            lblMoney.setText(Integer.toString(stat.getCash()));
            btnRent.setVisible(false);
            
        }
    }//GEN-LAST:event_btnRentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnWork;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
