/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss.presentation.ui;
import amiss.domain.model.User;
import amiss.domain.validation.Validation;

import amiss.domain.model.ActionResult;
import amiss.application.service.GameServices;
import amiss.application.service.JobService;
import amiss.application.service.StatsService;
import amiss.application.service.TimeService;

/**
 * The Fast Food Place Screen
 * @author The Rourke
 */
public class FastFoodGUI extends javax.swing.JFrame {

    /**
     * Creates new form FastFoodGUI
     */
    User user;
    GameServices services;

    private TimeService dist;
    private JobService job;
    private StatsService stat;

    /**
     *
     * @param u user object
     * @param d db object
     */
    public FastFoodGUI(User u, GameServices services) {
        initComponents();

        user = u;
        this.services = services;
        dist = services.time();
        job = services.jobs();
        stat = services.stats();

        lblTimer.setText(dist.readClock()); //gets the time left in the round
        lblMoney.setText(Integer.toString(stat.getCash())); //gets the users cash

        btnWork.setVisible(false);

        String loc = job.getLocation(); //checks if the user works at this location
        if (loc.equals("Monolith Burgers")) {
            btnWork.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuger = new javax.swing.JLabel();
        btnBuger = new javax.swing.JButton();
        btnCheeseBuger = new javax.swing.JButton();
        lblCheeseBuger = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblCash = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        btnWork = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        lblBugerDouble = new javax.swing.JLabel();
        btnBurgerDouble = new javax.swing.JButton();
        btnMilkshake = new javax.swing.JButton();
        lblMilkshake = new javax.swing.JLabel();
        lblFries = new javax.swing.JLabel();
        btnFamilyMeal = new javax.swing.JButton();
        lblFamilyMeal = new javax.swing.JLabel();
        btnFries = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monolith Burgers");
        setMinimumSize(new java.awt.Dimension(400, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuger.setText("Burger");
        getContentPane().add(lblBuger, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 140, 27));

        btnBuger.setText("32");
        btnBuger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBugerActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuger, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        btnCheeseBuger.setText("36");
        btnCheeseBuger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBugerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseBuger, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        lblCheeseBuger.setText("Cheese Burger");
        getContentPane().add(lblCheeseBuger, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 140, 30));

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 59, 40));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 72, 40));
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 72, 26));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 36));

        lblCash.setText("Cash");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 59, 26));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        txaNotification.setText("Welcome to Monolith Burgers.\nWhere our patties arent fried\nor boilded, but poached");
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 180));

        btnWork.setText("Work");
        btnWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkActionPerformed(evt);
            }
        });
        getContentPane().add(btnWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, 36));

        lblMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMenu.setText("Menu");
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 77, 35));

        lblBugerDouble.setText("Double Patty Cheese");
        getContentPane().add(lblBugerDouble, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 127, 27));

        btnBurgerDouble.setText("40");
        btnBurgerDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBugerActionPerformed(evt);
            }
        });
        getContentPane().add(btnBurgerDouble, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        btnMilkshake.setText("22");
        btnMilkshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBugerActionPerformed(evt);
            }
        });
        getContentPane().add(btnMilkshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        lblMilkshake.setText("Milkshake");
        getContentPane().add(lblMilkshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 140, 30));

        lblFries.setText("Fries");
        getContentPane().add(lblFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 127, 27));

        btnFamilyMeal.setText("50");
        btnFamilyMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBugerActionPerformed(evt);
            }
        });
        getContentPane().add(btnFamilyMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        lblFamilyMeal.setText("Family Meal");
        getContentPane().add(lblFamilyMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 140, 30));

        btnFries.setText("20");
        btnFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBugerActionPerformed(evt);
            }
        });
        getContentPane().add(btnFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        lblBackground.setIcon(amiss.presentation.assets.Assets.icon("screens/FastFood.png"));
        lblBackground.setMaximumSize(new java.awt.Dimension(400, 360));
        lblBackground.setMinimumSize(new java.awt.Dimension(400, 360));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBugerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBugerActionPerformed
        ActionResult result = stat.eatMain(Validation.parseIntOrDefault(evt.getActionCommand(), 0)); //checks if the user has enough time and money to purcahse item
        txaNotification.setText(txaNotification.getText() + result.message());
        if (result.timer() != null) {
            lblTimer.setText(result.timer());
        }
        if (result.money() != null) {
            lblMoney.setText(result.money());
        }
    }//GEN-LAST:event_btnBugerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, services).setVisible(true);
        FastFoodGUI.this.dispose();

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkActionPerformed
        ActionResult result = stat.workMain(); //checks if the user has enough time to work and updates their cash
        txaNotification.setText(txaNotification.getText() + result.message());
        if (result.timer() != null) {
            lblTimer.setText(result.timer());
        }
        if (result.money() != null) {
            lblMoney.setText(result.money());
        }
    }//GEN-LAST:event_btnWorkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuger;
    private javax.swing.JButton btnBurgerDouble;
    private javax.swing.JButton btnCheeseBuger;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFamilyMeal;
    private javax.swing.JButton btnFries;
    private javax.swing.JButton btnMilkshake;
    private javax.swing.JButton btnWork;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBuger;
    private javax.swing.JLabel lblBugerDouble;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblCheeseBuger;
    private javax.swing.JLabel lblFamilyMeal;
    private javax.swing.JLabel lblFries;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMilkshake;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
