/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss.presentation.ui;

import amiss.application.port.HelpRepository;
import amiss.application.port.PersistenceFailureException;
import amiss.infrastructure.GameContext;
import java.util.Optional;

/**
 * The Help Screen
 * @author The Rourke
 */
public class HelpGUI extends javax.swing.JFrame {

    /**
     * Creates new form HelpGUI
     */
    public HelpGUI() {
        initComponents();
    }
    HelpRepository help = new GameContext().help();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoadGame = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        btnLogin = new javax.swing.JButton();
        btnSAQ = new javax.swing.JButton();
        btnControls = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHowToWin = new javax.swing.JButton();
        btnTips = new javax.swing.JButton();
        btnGetJob = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Help");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoadGame.setText("Load Game");
        btnLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 162, -1));

        btnCreateUser.setText("Create New User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 162, -1));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setLineWrap(true);
        txaNotification.setRows(5);
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 13, 335, 280));

        btnLogin.setText("Logging In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 162, -1));

        btnSAQ.setText("Save And Exit");
        btnSAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnSAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 162, -1));

        btnControls.setText("Controls");
        btnControls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnControls, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 162, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 162, -1));

        btnHowToWin.setText("How to Win");
        btnHowToWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnHowToWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 162, -1));

        btnTips.setText("Tips");
        btnTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnTips, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 162, -1));

        btnGetJob.setText("Getting A Job");
        btnGetJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 162, -1));

        lblBackground.setIcon(amiss.presentation.assets.Assets.icon("screens/Help.png"));
        lblBackground.setMaximumSize(new java.awt.Dimension(540, 339));
        lblBackground.setMinimumSize(new java.awt.Dimension(540, 339));
        lblBackground.setName(""); // NOI18N
        lblBackground.setOpaque(true);
        lblBackground.setPreferredSize(new java.awt.Dimension(540, 339));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadGameActionPerformed
        try {
            String topic = evt.getActionCommand();
            Optional<String> description = help.findDescription(topic);
            txaNotification.setText(description.map(desc -> topic + "\n\n" + desc + "\n").orElse("")); //sets the text field with the description
        } catch (PersistenceFailureException ex) {
            txaNotification.setText("Can't Load Help"); //message guide to the user
        }
    }//GEN-LAST:event_btnLoadGameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnControls;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnGetJob;
    private javax.swing.JButton btnHowToWin;
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSAQ;
    private javax.swing.JButton btnTips;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
