package amiss.presentation.ui;

import amiss.application.port.PersistenceFailureException;
import amiss.application.port.UserRepository;
import amiss.infrastructure.GameContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author The Rourke
 */
public class HighScoreGUI extends javax.swing.JFrame {

    private static final Logger log = LoggerFactory.getLogger(HighScoreGUI.class);

    /**
     * Creates new form HighScoreGUI
     */
    public HighScoreGUI() {
        initComponents();
    }
    UserRepository users = new GameContext().users();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaHighScore = new javax.swing.JTextArea();
        btnShowHighScore = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HighScore");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaHighScore.setEditable(false);
        txaHighScore.setColumns(20);
        txaHighScore.setRows(5);
        txaHighScore.setToolTipText("");
        jScrollPane1.setViewportView(txaHighScore);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, 457, 337));

        btnShowHighScore.setText("Show HighScore");
        btnShowHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowHighScoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowHighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 363, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 363, 120, -1));

        lblBackground.setIcon(amiss.presentation.assets.Assets.icon("screens/HighScore.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 480, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowHighScoreActionPerformed
        try {
            String temp = "";
            for (String[] row : users.highScores()) {
                temp = temp + row[0] + "\t\t\t" + row[1] + "\n";
            }
            txaHighScore.setText(temp);
        } catch (PersistenceFailureException ex) {
            log.warn("Failed to load high scores", ex);
        }
    }//GEN-LAST:event_btnShowHighScoreActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScoreGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnShowHighScore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextArea txaHighScore;
    // End of variables declaration//GEN-END:variables
}
