/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss.presentation.ui;
import amiss.domain.model.User;

import amiss.application.service.GameServices;
import amiss.application.service.StatsService;
import amiss.application.service.TimeService;

/**
 * The Residence Screen
 * @author The Rourke
 */
public class LowClassResidenceGUI extends javax.swing.JFrame {

    /**
     * Creates new form LowClassResidenceGUI
     */
    User user;
    GameServices services;
    
    private TimeService dist;
    private StatsService stat;

    /**
     *
     * @param u user object
     * @param services the wired game services for the current player
     */
    public LowClassResidenceGUI(User u, GameServices services) {
        initComponents();

        user = u;
        this.services = services;
        dist = services.time();
        stat = services.stats();

        lblTimer.setText(dist.getNewTime(0)); //gets the time left in the round
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnStartNewRound = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnRelax = new javax.swing.JButton();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Low Class Housing");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 26, 60, 33));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 26, 46, 33));

        btnStartNewRound.setText("Start Next Round");
        btnStartNewRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartNewRoundActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartNewRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 225, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 262, -1, -1));

        btnRelax.setText("Relax (6h)");
        btnRelax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelaxActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 262, -1, -1));

        txaNotification.setEditable(false);
        txaNotification.setColumns(10);
        txaNotification.setLineWrap(true);
        txaNotification.setRows(6);
        txaNotification.setTabSize(4);
        txaNotification.setText("Upon Clicking the\nStart Next Round \nButton, you wil be\ndirected back to\nboard and the next\nround will start.");
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, 163, 141));

        lblBackground.setIcon(amiss.presentation.assets.Assets.icon("screens/Residence.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, services).setVisible(true);
        LowClassResidenceGUI.this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed
    
    private void btnStartNewRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartNewRoundActionPerformed

        dist.setTime(0); //retunrs the user back to the game screen to start next round
        new MainGameGUI(user, services).setVisible(true);
        LowClassResidenceGUI.this.dispose();

    }//GEN-LAST:event_btnStartNewRoundActionPerformed

    private void btnRelaxActionPerformed(java.awt.event.ActionEvent evt) {
        String time = dist.getNewTime(6); //relaxing at home costs 6 hours
        if (time.equals("Not Enough Time")) {
            txaNotification.setText(txaNotification.getText() + "\n\n" + time);
        } else {
            txaNotification.setText(txaNotification.getText() + "\nYou relax at home. One point in Happiness.");
            stat.updateHappiness();
            lblTimer.setText(time);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRelax;
    private javax.swing.JButton btnStartNewRound;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables

}
