/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss.presentation.ui;
import amiss.domain.model.User;

import amiss.application.service.EducationService;
import amiss.application.service.GameServices;
import amiss.application.service.StatsService;
import amiss.application.service.TimeService;
import amiss.application.service.TimeSpend;

/**
 * The University Screen
 * @author The Rourke
 */
public class UniversityGUI extends javax.swing.JFrame {

    /**
     * Creates new form UniversityGUI
     */
    User user;
    GameServices services;

    private TimeService dist;
    private StatsService stat;
    private EducationService uni;

    static String[] studyArr = {"Junior College", "Academic", "Year 3", "Year 4", "Graduate School", "Post Doctoral", "Research", "Publishing"}; //Array of degrees the user studies

    /**
     *
     * @param u user object
     * @param d db object
     */
    public UniversityGUI(User u, GameServices services) {
        initComponents();

        user = u;
        this.services = services;
        dist = services.time();
        stat = services.stats();
        uni = services.education();

        lblTimer.setText(dist.readClock()); //gets the time left in the round

        btnEnroll.setVisible(false);

        int prog = uni.getProg(); //checks the education level of the user
        if (uni.getEducation() != 8) {
            lblCurrDegree.setText(studyArr[uni.getEducation()]);
        }

        if (uni.getEducation() == 8) { //checks how much the user still needs to study
            btnEnroll.setVisible(false);
            lblFee.setVisible(false);
            btnStudy.setVisible(false);
            txfProg.setVisible(false);
            lblProgress.setVisible(false);
            lblCurrDegree.setVisible(false);
            txaNotification.setText("You have finished Hi-Tech U!");
        } else if (prog == 1) {
            btnEnroll.setVisible(false);
            btnStudy.setVisible(true);
            //lblCurrDegree.setText(studyArr[uni.getEducation()]);
            txfProg.setText("0/10");
        } else if (prog == 0) {
            btnEnroll.setVisible(true);
            btnStudy.setVisible(false);
            //lblCurrDegree.setText(studyArr[uni.getEducation()]);
        } else {
            txfProg.setText(uni.getProg() - 1 + "/10");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        lblCurrDegree = new javax.swing.JLabel();
        txfProg = new javax.swing.JTextField();
        btnStudy = new javax.swing.JButton();
        lblProgress = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        btnEnroll = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblFee = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 218, 71, 54));

        lblCurrDegree.setText("No Degree Selected");
        getContentPane().add(lblCurrDegree, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 58, 155, 50));

        txfProg.setEditable(false);
        getContentPane().add(txfProg, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 58, 50, 50));

        btnStudy.setText("Study");
        btnStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudy, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 58, 81, 50));

        lblProgress.setText("Progress");
        getContentPane().add(lblProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 30, -1, -1));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 161, 50, 50));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 115, 282, 157));

        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 26, -1, -1));

        lblTime.setText("Time:");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 133, 50, -1));

        lblFee.setText("Fee: R50");
        getContentPane().add(lblFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 30, -1, -1));

        lblBackground.setIcon(amiss.presentation.assets.Assets.icon("screens/University.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, services).setVisible(true);
        UniversityGUI.this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyActionPerformed

        int prog = uni.getProg();

        TimeSpend spend = dist.spendMinutes(services.costs().studyMinutes()); //time left after the user studies
        if (spend.rejected()) {
            txaNotification.setText(txaNotification.getText() + "\nNot Enough Time");
        } else {
            lblTimer.setText(TimeService.format(spend.remainingMinutes()));

            prog += 1;
            uni.setProg(prog);

            txfProg.setText(prog - 1 + "/10");
            if (prog == 11) {
                txaNotification.setText(txaNotification.getText() + "\n\nWell Done You have Completed: " + studyArr[uni.getEducation()]);
                uni.setEducation();
                btnEnroll.setVisible(true);
                btnStudy.setVisible(false);
                uni.setProg(0);
                txfProg.setText("0/10");

                if (uni.getEducation() == 8 && prog == 11) {
                    txaNotification.setText("You have completed Hi-Tech U");
                    lblCurrDegree.setVisible(false);
                    btnEnroll.setVisible(false);
                    lblFee.setVisible(false);
                    lblProgress.setVisible(false);
                    txfProg.setVisible(false);
                } else {
                    lblCurrDegree.setText(studyArr[uni.getEducation()]);
                }
            }
        }
    }//GEN-LAST:event_btnStudyActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed

        String cash = stat.buy("50");
        TimeSpend spend = dist.spendMinutes(0);
        if (spend.rejected()) {
            txaNotification.setText(txaNotification.getText() + "\nNot Enough Time");
        } else {
            if (cash.contains("not enough")) {
                txaNotification.setText(txaNotification.getText() + "\n\nYou Do Not Have Enough Cash");
            } else {
                int degree = uni.getEducation();
                btnEnroll.setVisible(false);
                
                txaNotification.setText(txaNotification.getText() + "\n\n" + cash);
                if (degree < 8) {
                    //uni.setEducation();
                    uni.setProg(1);
                    lblTimer.setText(TimeService.format(spend.remainingMinutes()));
                    btnEnroll.setVisible(false);
                    btnStudy.setVisible(true);
                    txfProg.setText("0/10");
                }
            }
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStudy;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCurrDegree;
    private javax.swing.JLabel lblFee;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    private javax.swing.JTextField txfProg;
    // End of variables declaration//GEN-END:variables
}
