/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss.presentation.ui;
import amiss.domain.model.User;

import amiss.application.service.GameServices;
import amiss.application.service.StatsService;
import amiss.application.service.TimeService;

/**
 * The Public Pool Screen
 * @author The Rourke
 */
public class PublicPoolGUI extends javax.swing.JFrame {

    /**
     * Creates new form PublicPoolGUI
     */
    User user;
    GameServices services;

    private TimeService dist;
    private StatsService stat;

    /**
     *
     * @param u user object
     * @param d db object
     */
    public PublicPoolGUI(User u, GameServices services) {
        initComponents();

        user = u;
        this.services = services;
        dist = services.time();
        stat = services.stats();
        lblTimer.setText(dist.getNewTime(0)); //gets the amount of time the user has this round
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnRelax = new javax.swing.JButton();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Public Pool");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 13, -1, -1));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 13, 70, 23));

        btnRelax.setText("Relax");
        btnRelax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelaxActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelax, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, 40));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        txaNotification.setText("Welcome To The Pool, At the\nPool eveytime you relax you \nwill earn one point towards\nyour happiness Goal.");
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 43, 250, 202));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 40));

        lblBackground.setIcon(amiss.presentation.assets.Assets.icon("screens/PublicPool.png"));
        lblBackground.setMaximumSize(new java.awt.Dimension(192, 290));
        lblBackground.setMinimumSize(new java.awt.Dimension(192, 290));
        lblBackground.setPreferredSize(new java.awt.Dimension(192, 290));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelaxActionPerformed
        String time = dist.getNewTime(6); //gets the time left in the round after user relaxes
        if (time.equals("Not Enough Time")) {
            txaNotification.setText(txaNotification.getText() + "\n\n" + time);
        } else {
            txaNotification.setText(txaNotification.getText() + "\nOne Point in Happiness");
            stat.updateHappiness();
            lblTimer.setText(time);
        }
    }//GEN-LAST:event_btnRelaxActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, services).setVisible(true);
        PublicPoolGUI.this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRelax;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
