/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

/**
 * The Clothes Store Screen
 * @author The Rourke
 */
public class ClothesStoreGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClothesStoreGUI
     */
    static User user;
    static DB db;

    static CalcDuration dist = new CalcDuration();
    static GetAJob job = new GetAJob();
    static Stats stat = new Stats();

    /**
     *
     * @param u user object
     * @param d db object
     */
    public ClothesStoreGUI(User u, DB d) {
        initComponents();

        user = u;
        db = d;

        lblTimer.setText(dist.getNewTime(0)); //displays the remaining time of the round
        lblMoney.setText(Integer.toString(stat.getCash())); //displays the users cash
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCasual = new javax.swing.JButton();
        btnFormal = new javax.swing.JButton();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        lblMoney = new javax.swing.JLabel();
        lblCash = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnSuit = new javax.swing.JButton();
        lblCasual = new javax.swing.JLabel();
        lblFormal = new javax.swing.JLabel();
        lblSuit = new javax.swing.JLabel();
        lblShop = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clothes Store");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCasual.setText("1");
        btnCasual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasualActionPerformed(evt);
            }
        });
        getContentPane().add(btnCasual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, 38));

        btnFormal.setText("2");
        btnFormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasualActionPerformed(evt);
            }
        });
        getContentPane().add(btnFormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 37));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txaNotification.setRows(5);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 140));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 79, 40));
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 72, 26));

        lblCash.setText("Cash");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 59, 26));

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 59, 26));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 72, 26));

        btnSuit.setText("3");
        btnSuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasualActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, 37));

        lblCasual.setText("Casual Clothes R20");
        getContentPane().add(lblCasual, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, 34));

        lblFormal.setText("Formal Clothes R35");
        getContentPane().add(lblFormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, 34));

        lblSuit.setText("Suit R55");
        getContentPane().add(lblSuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 112, 34));

        lblShop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblShop.setText("SHOP");
        getContentPane().add(lblShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 89, 46));

        lblBackground.setIcon(amiss.Assets.icon("screens/ClothesStore.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        ClothesStoreGUI.this.dispose(); //closes the screen

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCasualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasualActionPerformed
        int price = 0;
        job.setClothes(Integer.parseInt(evt.getActionCommand()),txaNotification);
        switch (evt.getActionCommand()) { //gets the price of the clothing item
            case "1":
                price = 20;
                break;
            case "2":
                price = 35;
                break;
            case "3":
                price = 55;
                break;
            default:
                txaNotification.setText("An Error occured"); //message guide to user
                break;
        }
        if (dist.getNewTime(0).equals("0:0")) { //checks if the user has enough time and cash to purchase an item
            txaNotification.setText(txaNotification.getText() + "\nRound Has Ended");
        } else if (stat.getCash() < price) {
            txaNotification.setText(txaNotification.getText() + "\nNot Enough Cash,\n You only have R" + stat.getCash());
            lblMoney.setText(Integer.toString(stat.getCash()));
        } else {
            lblTimer.setText(dist.getNewTime(1));

            txaNotification.setText(txaNotification.getText() + "\n" + stat.buy(Integer.toString(price)));
            lblMoney.setText(Integer.toString(stat.getCash()));
        }
    }//GEN-LAST:event_btnCasualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClothesStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClothesStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClothesStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClothesStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClothesStoreGUI(user, db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasual;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFormal;
    private javax.swing.JButton btnSuit;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblCasual;
    private javax.swing.JLabel lblFormal;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblShop;
    private javax.swing.JLabel lblSuit;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
