/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

/**
 * The Employment Office Screen
 * @author The Rourke
 */
public class EmploymentGUI extends javax.swing.JFrame {

    /**
     * Creates new form EmploymentGUI
     */
    static User user;
    static DB db;

    static CalcDuration dist = new CalcDuration();
    static GetAJob job = new GetAJob();

    /**
     *
     * @param u user object
     * @param d db object
     */
    public EmploymentGUI(User u, DB d) {
        initComponents();

        user = u;
        db = d;

        lblTimer.setText(dist.getNewTime(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        lblHeading = new javax.swing.JLabel();
        lblFastFoodPlace = new javax.swing.JLabel();
        lblApplianceStore = new javax.swing.JLabel();
        lblFactory = new javax.swing.JLabel();
        lblMarket = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();
        lblRentOffice = new javax.swing.JLabel();
        btnCook = new javax.swing.JButton();
        btnClerk = new javax.swing.JButton();
        btnAssistantManager = new javax.swing.JButton();
        btnSalesPerson = new javax.swing.JButton();
        btnRepairsman = new javax.swing.JButton();
        btnStoreManager = new javax.swing.JButton();
        btnSecretary = new javax.swing.JButton();
        btnMachanist = new javax.swing.JButton();
        btnEngineer = new javax.swing.JButton();
        btnBankJanitor = new javax.swing.JButton();
        btnBankAssistantManager = new javax.swing.JButton();
        btnBroker = new javax.swing.JButton();
        btnMarketJanitor = new javax.swing.JButton();
        btnChecker = new javax.swing.JButton();
        btnButcher = new javax.swing.JButton();
        btnRentOfficeJanitor = new javax.swing.JButton();
        btnApartmentManager = new javax.swing.JButton();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employment Office");
        setMinimumSize(new java.awt.Dimension(810, 500));
        getContentPane().setLayout(null);

        lblHeading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeading.setText("Apply For A Job");
        getContentPane().add(lblHeading);
        lblHeading.setBounds(170, 20, 181, 43);

        lblFastFoodPlace.setText("Fast Food Place");
        getContentPane().add(lblFastFoodPlace);
        lblFastFoodPlace.setBounds(12, 62, 90, 16);

        lblApplianceStore.setText("Appliance Store");
        getContentPane().add(lblApplianceStore);
        lblApplianceStore.setBounds(12, 117, 90, 16);

        lblFactory.setText("Factory");
        getContentPane().add(lblFactory);
        lblFactory.setBounds(14, 172, 90, 16);

        lblMarket.setText("Market");
        getContentPane().add(lblMarket);
        lblMarket.setBounds(12, 227, 90, 16);

        lblBank.setText("Bank");
        getContentPane().add(lblBank);
        lblBank.setBounds(12, 282, 80, 16);

        lblRentOffice.setText("Rent Office");
        getContentPane().add(lblRentOffice);
        lblRentOffice.setBounds(12, 337, 63, 16);

        btnCook.setText("Cook");
        btnCook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnCook);
        btnCook.setBounds(12, 85, 147, 25);

        btnClerk.setText("Clerk");
        btnClerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnClerk);
        btnClerk.setBounds(166, 85, 169, 25);

        btnAssistantManager.setText("Assistant Manager");
        btnAssistantManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnAssistantManager);
        btnAssistantManager.setBounds(344, 85, 148, 25);

        btnSalesPerson.setText("SalesPerson");
        btnSalesPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalesPerson);
        btnSalesPerson.setBounds(14, 140, 147, 25);

        btnRepairsman.setText("Repairsman");
        btnRepairsman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnRepairsman);
        btnRepairsman.setBounds(168, 140, 169, 25);

        btnStoreManager.setText("Store Manager");
        btnStoreManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnStoreManager);
        btnStoreManager.setBounds(344, 140, 148, 25);

        btnSecretary.setText("Secretary");
        btnSecretary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecretary);
        btnSecretary.setBounds(12, 195, 148, 25);

        btnMachanist.setText("Machinist");
        btnMachanist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnMachanist);
        btnMachanist.setBounds(168, 195, 169, 25);

        btnEngineer.setText("Engineer");
        btnEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnEngineer);
        btnEngineer.setBounds(345, 195, 147, 25);

        btnBankJanitor.setText("Bank Janitor");
        btnBankJanitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBankJanitor);
        btnBankJanitor.setBounds(12, 305, 147, 25);

        btnBankAssistantManager.setText("Bank Assistant Manager");
        btnBankAssistantManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBankAssistantManager);
        btnBankAssistantManager.setBounds(166, 305, 170, 25);

        btnBroker.setText("Broker");
        btnBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBroker);
        btnBroker.setBounds(345, 305, 147, 25);

        btnMarketJanitor.setText("Market Janitor");
        btnMarketJanitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarketJanitor);
        btnMarketJanitor.setBounds(12, 250, 147, 25);

        btnChecker.setText("Checker");
        btnChecker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnChecker);
        btnChecker.setBounds(166, 250, 169, 25);

        btnButcher.setText("Butcher");
        btnButcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnButcher);
        btnButcher.setBounds(346, 250, 146, 25);

        btnRentOfficeJanitor.setText("Rent Office Janitor");
        btnRentOfficeJanitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnRentOfficeJanitor);
        btnRentOfficeJanitor.setBounds(12, 360, 147, 25);

        btnApartmentManager.setText("Apartment Manager");
        btnApartmentManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookActionPerformed(evt);
            }
        });
        getContentPane().add(btnApartmentManager);
        btnApartmentManager.setBounds(166, 360, 170, 25);

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setLineWrap(true);
        txaNotification.setRows(5);
        txaNotification.setText("Welcome to the Employment Office. Here is where you will be able to select a Job and start earing money. \n\nPick your Career wisely as takes 10 minutes everytime you select one.\n\nIf you know you don't have qualification for a career don't try select it as it will say you dont have enough education. Once you complete a degree at University you will be told what jobs you can apply to.\n\nThe safest option if you looking for you 1st job will be a Janitor. ");
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay);
        pnlDisplay.setBounds(500, 40, 281, 371);

        lblTime.setText("Time:");
        getContentPane().add(lblTime);
        lblTime.setBounds(570, 10, 34, 17);
        getContentPane().add(lblTimer);
        lblTimer.setBounds(610, 10, 91, 17);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(610, 420, 53, 25);

        lblBackground.setBackground(new java.awt.Color(135, 204, 250));
        lblBackground.setIcon(amiss.Assets.icon("screens/Employment.png"));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookActionPerformed
        if (dist.getNewTime(0).equals("0:0")) { //checks if the user enough time to apply for a job
            txaNotification.setText(txaNotification.getText() + "\n\nRound Has Ended");
        } else { //checks if the user has enough education for a job
            lblTimer.setText(dist.getNewTime(1));
            String jb = job.applyForJob(evt.getActionCommand(),txaNotification);
            txaNotification.setText(txaNotification.getText() + "\n\n" + jb);
        }
    }//GEN-LAST:event_btnCookActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        EmploymentGUI.this.dispose();

    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmploymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmploymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmploymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmploymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmploymentGUI(user, db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApartmentManager;
    private javax.swing.JButton btnAssistantManager;
    private javax.swing.JButton btnBankAssistantManager;
    private javax.swing.JButton btnBankJanitor;
    private javax.swing.JButton btnBroker;
    private javax.swing.JButton btnButcher;
    private javax.swing.JButton btnChecker;
    private javax.swing.JButton btnClerk;
    private javax.swing.JButton btnCook;
    private javax.swing.JButton btnEngineer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMachanist;
    private javax.swing.JButton btnMarketJanitor;
    private javax.swing.JButton btnRentOfficeJanitor;
    private javax.swing.JButton btnRepairsman;
    private javax.swing.JButton btnSalesPerson;
    private javax.swing.JButton btnSecretary;
    private javax.swing.JButton btnStoreManager;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel lblApplianceStore;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblFactory;
    private javax.swing.JLabel lblFastFoodPlace;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMarket;
    private javax.swing.JLabel lblRentOffice;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
