/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

/**
 * The Factory Screen
 * @author The Rourke
 */
public class FactoryGUI extends javax.swing.JFrame {

    /**
     * Creates new form FactoryGUI
     */
    static User user;
    static DB db;

    static CalcDuration dist = new CalcDuration();
    static GetAJob job = new GetAJob();
    static Stats stat = new Stats();

    /**
     *
     * @param u user object
     * @param d db object
     */
    public FactoryGUI(User u, DB d) {
        initComponents();

        user = u;
        db = d;

        lblTimer.setText(dist.getNewTime(0)); //gets the time left in the round
        lblMoney.setText(Integer.toString(stat.getCash())); //gets the users cash

        btnWork.setVisible(false);

        String loc = job.getLocation(); //checks if the user works at this location
        if (loc.equals("Factory")) {
            btnWork.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWork = new javax.swing.JButton();
        lblMoney = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblCash = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblTimer = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factory");
        setMinimumSize(null);
        setName("Factory"); // NOI18N
        setPreferredSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWork.setText("Work");
        btnWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkActionPerformed(evt);
            }
        });
        getContentPane().add(btnWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 290, 110, 36));
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 53, 72, 26));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        txaNotification.setText("Welcome to the Factory");
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, 260, 187));

        lblCash.setText("Cash");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, 59, 26));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 36));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 13, 72, 26));

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 59, 26));

        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\The Rourke\\Desktop\\Rourke\\Grade 12\\IT\\IT PAT\\Screens\\Factory.png")); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 290, 350));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkActionPerformed
        stat.workMain(txaNotification, lblTimer, lblMoney); //checks if the user has enough time to work and updated their cash
    }//GEN-LAST:event_btnWorkActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        FactoryGUI.this.dispose(); //closes the screen
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactoryGUI(user, db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnWork;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
