/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

/**
 * The Residence Screen
 * @author The Rourke
 */
public class LowClassResidenceGUI extends javax.swing.JFrame {

    /**
     * Creates new form LowClassResidenceGUI
     */
    static User user;
    static DB db;
    
    CalcDuration dist = new CalcDuration();
    Food eat = new Food();
    
    /**
     *
     * @param u user object
     * @param d db object
     */
    public LowClassResidenceGUI(User u, DB d) {
        initComponents();
        
        user = u;
        db = d;
        
        lblTimer.setText(dist.getNewTime(0)); //gets the time left in the round
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnStartNewRound = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Low Class Housing");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 26, 60, 33));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 26, 46, 33));

        btnStartNewRound.setText("Start Next Round");
        btnStartNewRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartNewRoundActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartNewRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 225, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 262, -1, -1));

        txaNotification.setEditable(false);
        txaNotification.setColumns(10);
        txaNotification.setLineWrap(true);
        txaNotification.setRows(6);
        txaNotification.setTabSize(4);
        txaNotification.setText("Upon Clicking the\nStart Next Round \nButton, you wil be\ndirected back to\nboard and the next\nround will start.");
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, 163, 141));

        lblBackground.setIcon(amiss.Assets.icon("screens/Residence.png"));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        LowClassResidenceGUI.this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed
    
    private void btnStartNewRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartNewRoundActionPerformed

        dist.setTime(0); //retunrs the user back to the game screen to start next round
        new MainGameGUI(user, db).setVisible(true);
        LowClassResidenceGUI.this.dispose();
        
    }//GEN-LAST:event_btnStartNewRoundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LowClassResidenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LowClassResidenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LowClassResidenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LowClassResidenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LowClassResidenceGUI(user, db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStartNewRound;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables

}
