/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amiss;

/**
 * The Pizza Palace Screen
 * @author The Rourke
 */
public class PizzaPalaceGUI extends javax.swing.JFrame {

    /**
     * Creates new form FastFoodGUI
     */
    static User user;
    static DB db;

    static CalcDuration dist = new CalcDuration();
    static Stats stat = new Stats();
    static Food eat = new Food();

    /**
     *
     * @param u user object
     * @param d db object
     */
    public PizzaPalaceGUI(User u, DB d) {
        initComponents();

        user = u;
        db = d;

        lblTimer.setText(dist.getNewTime(0)); //gets the time left in the round
        lblMoney.setText(Integer.toString(stat.getCash())); //gets the users cash


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMargarita = new javax.swing.JLabel();
        btnMargarita = new javax.swing.JButton();
        btnRegina = new javax.swing.JButton();
        lblRegina = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblCash = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JScrollPane();
        txaNotification = new javax.swing.JTextArea();
        lblMenu = new javax.swing.JLabel();
        lblHawaii = new javax.swing.JLabel();
        btnHawaii = new javax.swing.JButton();
        btnSalmone = new javax.swing.JButton();
        lblSalmone = new javax.swing.JLabel();
        lblTonno = new javax.swing.JLabel();
        btnArlecchino = new javax.swing.JButton();
        lblArlecchino = new javax.swing.JLabel();
        btnTonno = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza Palace");
        setMinimumSize(new java.awt.Dimension(400, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMargarita.setText("Margarita");
        getContentPane().add(lblMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 127, 27));

        btnMargarita.setText("52");
        btnMargarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        btnRegina.setText("65");
        btnRegina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegina, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        lblRegina.setText("Regina");
        getContentPane().add(lblRegina, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 50, 20));

        lblTime.setText("Time");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 59, 40));
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 72, 40));
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 72, 26));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 36));

        lblCash.setText("Cash");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 59, 26));

        txaNotification.setEditable(false);
        txaNotification.setColumns(20);
        txaNotification.setRows(5);
        txaNotification.setText("Welcome to pizza palace, where\ncustomer satisfaction is number\nfirst");
        txaNotification.setWrapStyleWord(true);
        pnlDisplay.setViewportView(txaNotification);

        getContentPane().add(pnlDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 200));

        lblMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMenu.setText("Pizza Palace Menu");
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 190, 35));

        lblHawaii.setText("Hawaii");
        getContentPane().add(lblHawaii, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 127, 27));

        btnHawaii.setText("72");
        btnHawaii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHawaii, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        btnSalmone.setText("85");
        btnSalmone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalmone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        lblSalmone.setText("Salmone");
        getContentPane().add(lblSalmone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 166, 130, 30));

        lblTonno.setText("Tonno");
        getContentPane().add(lblTonno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 127, 27));

        btnArlecchino.setText("87");
        btnArlecchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });
        getContentPane().add(btnArlecchino, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        lblArlecchino.setText("Arlecchino");
        getContentPane().add(lblArlecchino, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 140, 30));

        btnTonno.setText("75");
        btnTonno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTonno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\The Rourke\\Desktop\\Rourke\\Grade 12\\IT\\IT PAT\\Screens\\Pizza.png")); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(400, 360));
        lblBackground.setMinimumSize(new java.awt.Dimension(400, 360));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMargaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMargaritaActionPerformed
        stat.eatMain(txaNotification, lblTimer, lblMoney, Integer.parseInt(evt.getActionCommand())); //checks if the user has enough time and money to purcahse item
    }//GEN-LAST:event_btnMargaritaActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new MainGameGUI(user, db).setVisible(true);
        PizzaPalaceGUI.this.dispose(); //closes the screen
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaPalaceGUI(user, db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArlecchino;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHawaii;
    private javax.swing.JButton btnMargarita;
    private javax.swing.JButton btnRegina;
    private javax.swing.JButton btnSalmone;
    private javax.swing.JButton btnTonno;
    private javax.swing.JLabel lblArlecchino;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblHawaii;
    private javax.swing.JLabel lblMargarita;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblRegina;
    private javax.swing.JLabel lblSalmone;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTonno;
    private javax.swing.JScrollPane pnlDisplay;
    private javax.swing.JTextArea txaNotification;
    // End of variables declaration//GEN-END:variables
}
